#!/usr/bin/env ruby

$debug = true

require 'pp'
require './netfpga'
require './xml_parser'

unless ARGV.size == 2
  puts "usage: #{$0} XML-config-file register-headers"
  exit 1
end

netfpga = NetFPGA.new ARGV.last

config = XMLParser.parse ARGV.first

pp config if $debug

config.each do |eth, params|
  i = eth[/\d$/].to_i

  netfpga.set_mac i, :local, params[:local]
  netfpga.set_mac i, :other, params[:other]

  netfpga.set_number_of_phases i, params[:phases].size

  params[:phases].each.with_index do |(type, length), ph|
    netfpga.set_phase_type   i, ph, type
    netfpga.set_phase_length i, ph, length
  end
end

(0..3).each do |i|
  puts "port #{i}"

  puts "\tlocal MAC: #{netfpga.get_mac i, :local}"
  puts "\tother MAC: #{netfpga.get_mac i, :other}"

  puts "\tnumber of phases: #{netfpga.get_number_of_phases i}"

  (0..7).each do |ph|
    puts "\tphase #{ph}: type: #{netfpga.get_phase_type i, ph}, length: #{netfpga.get_phase_length i, ph}"
  end
end
